### ISSUE TITLE
AndroidManifest.xml' which doesn't exist

### ISSUE THREAD

**Issue by SirFilbido** [pererikbergman/multiplatform-flavors#2]
I did the implementation as the example, but when running the command for the development environment, the following problem occurs:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':config:development:processDebugMainManifest' (type 'ProcessApplicationManifest').
  - In plugin 'com.android.internal.version-check' type 'com.android.build.gradle.tasks.ProcessApplicationManifest' property 'mainManifest' specifies file '...project-kmp/config/development/src/androidMain/AndroidManifest.xml' which doesn't exist.
    
    Reason: An input file was expected to be present but it doesn't exist.
```

I found it strange that he complained about AndroidManifest and having to add it to each flavor, I believe that this is not a good path.

**Comment by pererikbergman** [comment]
Check if the config modules are **androidLibrary** or **androidApplication**, if they are **androidApplication** require AndroidManifest while the **androidLibrary** doesn't. 

Do you have a repo where you get this error that you can share?

**Comment by pererikbergman** [comment]
Other people had same issue, they used the **androidApplication** instead of **androidLibrary**, closing issue.
